### ISSUE TITLE
Default piston.rs to HTTPS

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/pistondevelopers.github.io#118]
See https://github.com/PistonDevelopers/piston/issues/1246

> Right now, www.piston.rs defaults to insecure HTTP. But https://www.piston.rs also works, but is just not default. 
>
> The Documentation and Blog links at the top should also default to HTTPS instead of HTTP. Modern browsers are showing warnings to users and may turn some users away from the site.

**Comment by bvssvni** [comment]
cc @leonkunert

**Comment by leonkunert** [comment]
I will check this out later today.

**Comment by leonkunert** [comment]
It was actually simpler than I thought:
<img width="813" alt="screen shot 2018-10-18 at 11 17 37" src="https://user-images.githubusercontent.com/1851804/47144341-8ebee480-d2c7-11e8-957b-271d5a3741c6.png">
