### ISSUE TITLE
Piston logo

### ISSUE THREAD

**Issue by rolandasb** [PistonDevelopers/pistondevelopers.github.io#89]
![](http://i.imgur.com/EdWn242.png)

Here's something I put together today. Anyone have more ideas?

**Comment by frewsxcv** [comment]
I would love to restart this conversation because the current GitHub Organization logo is......not great :)

Anyone have strong opinions on the designs already presented or have any thoughts on additional designs?

**Comment by bvssvni** [comment]
One idea is to use something else than a piston from a car engine into something more recognizable. Since Piston is a game engine, it could be something game related.

**Comment by frewsxcv** [comment]
There are [various Creative Commons licensed 'piston' icons on NounProject](https://thenounproject.com/search/?q=piston) we could utilize

**Comment by fenhl** [comment]
I really like the idea of incorporating the Rust logo.

**Comment by frewsxcv** [comment]
> I really like the idea of incorporating the Rust logo.

A couple examples of this in practice already

https://github.com/georust

https://github.com/rustaudio
